name: technozarre
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  logger: ^1.0.0
  rive: ^0.10.4
  shared_preferences: ^2.0.6
  ionicons: ^0.2.2
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


  
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/favicon.png
    - assets/bgg12.gif
  
    - assets/posters/Board Meeting.png
    - assets/posters/Animie Quiz.jpg
    - assets/posters/Autocad.png
    - assets/posters/Code War.jpg
    - assets/posters/Fiber Structure.png
    - assets/posters/Debate.jpg
    - assets/posters/Digital Handicraft.png
    - assets/posters/digital illustration.png
    - assets/posters/Human Ludo.png
    - assets/posters/Press RElease.jpg
    - assets/posters/pun war.png
    - assets/posters/Masala Allocation.png
    - assets/posters/Offline Gaming.png
    - assets/posters/Online Gaming.png
    - assets/posters/PPT Competition.png
    - assets/posters/Cultural Night.png
    - assets/posters/DJ Night.png
    - assets/posters/Exhibition.png
    - assets/posters/fashion show.png
    - assets/posters/Hackathon.png
    - assets/posters/MUN.png
    - assets/posters/Open Mic.png
    - assets/posters/Photography.png
    - assets/posters/robot war.png
    - assets/posters/tech quiz.png
    - assets/posters/tresure hunt.png
    - assets/posters/structural engineering.png
    - assets/hl.png
    - assets/login.riv

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
